### ISSUE TITLE
Blende 2.82

### ISSUE THREAD

**Issue by Tetwisted** [jasonicarter/create-isocam#1]
Can you make it for the new update?

**Comment by archelangelo** [comment]
For anyone who's been wondering, add `register()` at the end of the code. Run. Then you'll find the "Create Isocam" option under the "Add" menu.

**Comment by LuisGrunfeldt** [comment]
> Can you make it for the new update?

> The addon is working, but it has changed the position i think. Try to Shift+tab+a and there is a option to "Create Isocam"
