### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by Hunam6** [jasonicarter/create-isocam#2]
I see no tab on the viewport.

**Comment by mishazawa** [comment]
Hello @Hunam6 
Press "t" and select Iso Camera 
![image](https://user-images.githubusercontent.com/7611372/133658984-79fe6ca3-4ac4-443a-90f0-f0bf26a7a0e5.png)

**Comment by jasonicarter** [comment]
Resolved with the latest merge
