### ISSUE TITLE
Doesn't show up in 2.92+

### ISSUE THREAD

**Issue by laffan** [jasonicarter/create-isocam#4]
Tried in 2.92 & 2.93. Installs fine, but isn't in the normal Shift + A menu or the Shift + Tab + A menu. 

MacBook Pro (Retina, 15-inch, Mid 2015 / 2.5 GHz Quad-Core Intel Core i7) /  MacOS 11.2.3

**Comment by Vanestefani** [comment]
i have the same problem

**Comment by laffan** [comment]
Also doesn't work for me.

**Comment by JensKrumsieck** [comment]
The file `createisocam.py` needs to be renamed to `__init__.py`.

* Install the Addon as usual. 
* Go to `%AppData%\Blender Foundation\Blender\{BLENDER VERSION}\scripts\addons\create-isocam-master` (Replace {BLENDER VERSION} with e.g. 2.93:  `%AppData%\Blender Foundation\Blender\2.93\scripts\addons\create-isocam-master` )
* Rename  `createisocam.py` to `__init__.py`.

**Comment by Syltech** [comment]
worked for me !
