### ISSUE TITLE
isocam causes errors in blender

### ISSUE THREAD

**Issue by Kinsley12off** [jasonicarter/create-isocam#8]
hi
i have a problem with the plugin when i try to use this addon to create a trueisocam, it says this

Python: Traceback (most recent call last):
  File "C:\Users\Kinsley12\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\createisocam.py", line 35, in execute
    bpy.ops.object.camera_add(location=(30.60861, -30.60861, 30.60861)) # Create Camera. I would love to set the rotation here too. Blender not. Not that there are no tutorials around which shows that it should work ... .
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.camera_add.poll() failed, context is incorrect

location: <unknown location>:-1

can you fix this error, please

**Comment by goodbyennn** [comment]
Me too.

**Comment by Helga108** [comment]
Try switching out of the edit mode by Tab. It helped me. Before that, in edit mode, I was getting the same error.
